distributable:
  url: https://github.com/launchbadge/sqlx/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/sqlx-cli

versions:
  github: launchbadge/sqlx/tags

build:
  dependencies:
    rust-lang.org: '>=1.56'
    rust-lang.org/cargo: '*'
  script: cargo install --locked --path sqlx-cli --root {{prefix}}

test:
  env:
    DATABASE_URL: sqlite://test.db
  script:
    - sqlx database create
    - sqlx migrate add create_users_table
    - sqlx migrate run
